### PR TITLE
Initialise each image with individual data-mage-init attributes

### PR DESCRIPTION
**Pull request by clockworkgeek**
This is simpler because several files used to insert an inline script tag are removed (inline scripts are generally considered bad practice).
Also mage-init will re-initialise when "contentUpdated" event is triggered, which in my experience is quite reliable even with 3rd party extensions like that encountered in #11.

### CODE REVIEW

**Comment by srenon** [comment]
@clockworkgeek... Thanks for the PR.

 I originally thought about similar solutions, but had 2 concerns so I decided to do it this way:

1. Compatible - can you have multiples data-mage-init on the same element? I think this would increase the chance of conflict with custom themes and extensions (ie https://www.magepal.com/catalog-hover-image-for-magento.html)
2. Speed - On average a PLP normally has 15 or more images which at a certain point I think it should be slower than just using one. This may also cause a lag on slower site since Magento seems to process data-mage-init from last to first 

Plus Magento 2.4, seem to come standard with lazy load, so I have not idea on what the future of this extension is. https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-images.html

**Comment by clockworkgeek** [comment]
Those are very good points.

1. I hadn't considered multiple attributes on the same element. It is not permitted and likely all but one will be ignored by the browser. The format of mage-init allows several declarations to be merged into one, I'll have a go at that in a while.
2. On the site which prompted this PR there are up to 100 product images on a page, I don't notice lag when looking at the page. Nor would I expect to since your "one" script is causing a loop to initialise all images, and my "individual" scripts are called in a loop and initialise one image each - effectively both `O(n)`. As a counterpoint an inline script is executed during the browser's parsing phase which causes a small delay before any content is seen, the data-mage-init attributes are not executed until the DOM loaded event which is after content is displayed once. We're probably splitting hairs over something unimportant.
3. I wasn't aware that Magento 2.4 had this as a feature. Your latest commit was for compatibility with v2.4 which is a bit contradictory. In reality many sites are slow to upgrade to the newest version but keep adding more add-ons and tweaks so there will still be a demand for some time.

**Comment by clockworkgeek** [comment]
You might be interested to know that Magento 2.4's trick is to add `loading="lazy"` to the [image template](https://github.com/magento/magento2/pull/27033/commits/1a7977570c2638a33c8cc90b253b061fc934fe2d). This is a fairly new feature and [not well supported yet](https://www.caniuse.com/#feat=loading-lazy-attr), so a JavaScript solution still has value for a while.

**Comment by srenon** [comment]
What if you check ``$result`` to see if ``data-mage-init`` exists if it does not do

            $replace = [
                'img class="swatch-option-loading ',
                sprintf(' data-mage-init=\'{"MagePalLazyLoad":{}}\' data-original="%s"', $orgImageUrl),
                sprintf(' data-mage-init=\'{"MagePalLazyLoad":{}}\' data-original="%s"', $orgImageUrl)
            ];

if it does exists then replace (in a new find/replace)

         data-mage-init='{"

With 

         data-mage-init='{"MagePalLazyLoad":{},

Not the cleanest but should be faster than XML operation. 

Also if a third party extension using similar after plug-in and has a lower sort order you will still have compatible issues

**Comment by clockworkgeek** [comment]
If `$result` contains the string `data-mage-init` there is no guarantee that it is within an `` tag. However checking for it's existence could be a good way of avoiding the slower method. I had hoped that the block's output would be cached and speed wouldn't be an issue, but now I see that caching occurs inside `toHtml()` and so before this plugin. Caching would be effective if we override `Magento\Catalog\Block\Product\Image` and it's protected `_toHtml()` method but that's more intrusive than a plugin.

**Comment by srenon** [comment]
Sorry I did not look at the content of $result. Couldn't we use a similar regular express to https://stackoverflow.com/questions/450108/regular-expression-to-extract-src-attribute-from-img-tag

**Comment by clockworkgeek** [comment]
I should have guessed, regular expressions are neater and faster, as usual.

**Pull request merged**
